#pragma once
#include <cstdint>

enum class ApricotCode : uint32_t
{
	SUCCESS = 0,
	UNKNOWN_ERROR,
	FAILED_MEM_ALLOC,
	FAILED_PE_MAP_SECTIONS,
	FAILED_PE_FINALIZE_SECTIONS,
	FAILED_PE_CALL_ENTRY_POINT,
	FAILED_ENTRY_POINT_FAILED,
	FAILED_LOAD_DEPENDENCIES,
};
