#pragma once
#include <cstdint>
#include <sstream>

enum class ErrorCode : uint8_t
{
	UNKNOWN_ERROR = 0,

	// Utilities
	FAILED_TIME_FORMAT_CONVERSION,
	FAILED_GET_COMMAND_LINE,
	FAILED_STRING_CONVERSION,

	// Generic
	UNCOVERED_ENUM_VALUE,
	OUT_OF_BOUNDS,
	INVALID_ARGUMENT,

	// Files
	FAILED_FILE_CREATE,
	FAILED_FILE_WRITE,
	FAILED_FILE_SEEK,
	FAILED_FILE_READ,

	// Process
	FAILED_PROCESS_OPEN,
	FAILED_PROCESS_QUERY_INFORMATION,
	FAILED_PROCESS_READ_MEMORY,
	FAILED_PROCESS_GET_PID,
	FAILED_PROCESS_GET_PATH,
	FAILED_PROCESS_GET_TIMES,
	FAILED_PROCESS_CREATE,
	FAILED_PROCESS_TERMINATE,
	FAILED_PROCESS_GET_MODULES,
	FAILED_PROCESS_GET_MAIN_MODULE,
	FAILED_PROCESS_GET_MODULE_FILENAME,

	// Thread
	FAILED_THREAD_CREATE,

	// Remote Memory
	FAILED_REMOTE_MEMORY_ALLOCATE,
	FAILED_REMOTE_MEMORY_WRITE,

	// Library
	FAILED_LIBRARY_GET_PROC_ADDRESS,
	FAILED_LIBRARY_LOAD,

	// Events
	FAILED_EVENT_OPEN,
	FAILED_EVENT_CREATE,
	FAILED_EVENT_SET,
	FAILED_WAIT,

	// Process Iterator
	FAILED_PROCESS_ITERATOR_CREATE,
	FAILED_PROCESS_ITERATOR_NEXT,

	// Apricot
	FAILED_APRICOT_LOAD,
	FAILED_APRICOT_GET,

	// Fig
	FAILED_FIG_INITIALIZE,
	FAILED_FIG_EXECUTE,
	FAILED_FIG_STATUS,
	FAILED_FIG_TAKE,
	FIG_ALREADY_LOADED,
	FIG_NOT_LOADED,
	FAILED_EVENT_WAIT,
	WAIT_TIMED_OUT,
	FAILED_SYSTEM_GET_COMPUTER_NAME,
	FAILED_SYSTEM_GET_VERSION,
	FAILED_SYSTEM_GET_USERNAME,
	FAILED_WMI_INITIALIZE,
	FAILED_WMI_CREATE_INSTANCE,
	FAILED_WMI_CONNECT_SERVER,
	FAILED_WMI_SET_PROXY,
	FAILED_WMI_INITIALIZE_SECURITY,
	FAILED_WMI_GET_PROPERTY,
	FAILED_WMI_QUERY,
	FAILED_WMI_ENUMERATE_RESULT,
	FAILED_WMI_VARIANT_TIME_CONVERSION,
	FAILED_SYSTEM_TIME_CONVERSION,
	WMI_UNSUPPORTED_VARIANT_TYPE,
};

std::wostringstream& operator<<(std::wostringstream& output, ErrorCode code);
