#pragma once
#include <cstdint>
#include <sstream>

enum class ErrorCode : uint8_t
{
	UNKNOWN_ERROR = 0,

	// Generic
	UNCOVERED_ENUM_VALUE,
	OUT_OF_BOUNDS,
	INVALID_ARGUMENT,
	ILLEGAL_OBJECT_STATE,
	NOT_ENOUGH_DATA,

	// Utilities
	FAILED_TIME_FORMAT_CONVERSION,
	FAILED_GET_COMMAND_LINE,
	FAILED_STRING_CONVERSION,
	FAILED_SYSTEM_TIME_CONVERSION,

	// Files
	FAILED_FILE_CREATE,
	FAILED_FILE_WRITE,
	FAILED_FILE_SEEK,
	FAILED_FILE_READ,
	FAILED_FILE_ITERATOR_START,
	FAILED_FILE_ITERATOR_NEXT,
	FAILED_FILE_GET_TIME,
	FAILED_FILE_SET_TIME,
	FAILED_FILE_GET_POSITION,

	// Volumes
	FAILED_VOLUME_FIND_FIRST,
	FAILED_VOLUME_GET_PATHS,
	FAILED_VOLUME_FIND_NEXT,

	// Process
	FAILED_PROCESS_OPEN,
	FAILED_PROCESS_QUERY_INFORMATION,
	FAILED_PROCESS_READ_MEMORY,
	FAILED_PROCESS_GET_PID,
	FAILED_PROCESS_GET_PATH,
	FAILED_PROCESS_GET_TIMES,
	FAILED_PROCESS_CREATE,
	FAILED_PROCESS_TERMINATE,
	FAILED_PROCESS_GET_MODULES,
	FAILED_PROCESS_GET_MAIN_MODULE,
	FAILED_PROCESS_GET_MODULE_FILENAME,

	// Thread
	FAILED_THREAD_CREATE,

	// Remote Memory
	FAILED_REMOTE_MEMORY_ALLOCATE,
	FAILED_REMOTE_MEMORY_WRITE,

	// Library
	FAILED_LIBRARY_GET_PROC_ADDRESS,
	FAILED_LIBRARY_LOAD,
	GENERIC_FUNCTION_EXCEPTION,

	// Events
	FAILED_EVENT_OPEN,
	FAILED_EVENT_CREATE,
	FAILED_EVENT_SET,
	FAILED_WAIT,
	WAIT_TIMED_OUT,

	// Process Iterator
	FAILED_PROCESS_ITERATOR_CREATE,
	FAILED_PROCESS_ITERATOR_NEXT,

	// WMI
	FAILED_WMI_INITIALIZE,
	FAILED_WMI_CREATE_INSTANCE,
	FAILED_WMI_CONNECT_SERVER,
	FAILED_WMI_SET_PROXY,
	FAILED_WMI_INITIALIZE_SECURITY,
	FAILED_WMI_GET_PROPERTY,
	FAILED_WMI_QUERY,
	FAILED_WMI_ENUMERATE_RESULT,
	FAILED_WMI_VARIANT_TIME_CONVERSION,
	WMI_UNSUPPORTED_VARIANT_TYPE,
	FAILED_SAFE_ARRAY_ACCESS,

	// Apricot
	FAILED_APRICOT_LOAD,
	FAILED_APRICOT_GET,

	// Fig
	FAILED_FIG_INITIALIZE,
	FAILED_FIG_EXECUTE,
	FAILED_FIG_STATUS,
	FAILED_FIG_TAKE,
	FIG_ALREADY_LOADED,
	FIG_NOT_LOADED,

	// Media
	FAILED_DC_GET,
	FAILED_DC_CREATE_COMPATIBLE,
	FAILED_BMP_CREATE_COMPATIBLE,
	FAILED_DC_SELECT_OBJECT,
	FAILED_BMP_INVALID_DC,
	FAILED_BMP_CAPTURE,
	FAILED_BMP_SERIALIZE,
};

std::wostringstream& operator<<(std::wostringstream& output, ErrorCode code);
