name: Full Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  solutions:
    runs-on: windows-latest

    outputs:
      files: ${{ steps.find_slns.outputs.sln_files }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find Solution Files
        id: find_slns
        run: echo "sln_files=$(find . -name '*.sln' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build:
    runs-on: windows-latest
    needs: solutions
    strategy:
      matrix:
        solution: ${{ fromJson(needs.solutions.outputs.files) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          Write-Host "🔧 Building solution: ${{ matrix.solution }}"
            msbuild ${{ matrix.solution }} /t:Build /p:Configuration=Release /m
          }
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: build-artifacts
            path: |
              **/Release/*.exe
              **/Release/*.dll
